#!/usr/bin/python3
#######################################################################
#                                                                     #
# This is an the install script to install Server Connect manually to #
# eliminate having to do it manually. It will set the path and alias  #
# to the where ever you have the install script saved so make sure    #
# you have it and  the connect.py script in the same directory        #
#                                                                     #
# This script also needs to be run as root                            #
#                                                                     #
#######################################################################

import os

# Copies file to /usr/local/bin then validates the 
# file copied successfully also makes sure ~/.ssh/ 
# folder exists so you don't run into errors later
homeDirSSH = os.path.expanduser("~/.ssh")
os.system("sudo cp connect.py /usr/local/bin/connect")
if(not os.path.isdir(homeDirSSH)):
    os.system("mkdir \""+homeDirSSH+"\"")
if(os.path.isfile("/usr/local/bin/connect")):
    print("Install Complete")
else:
    print("An error occured")
