#!/usr/bin/python3
#######################################################################
#                                                                     #
# This is an the uninstall script to remove Server Connect to         #
# eliminate having to do it manually.                                 #
#                                                                     #
#######################################################################

import os

# Deletes connect from /usr/local/bin and connections.txt
# from the ~/.ssh folder and verifies they both have been
# sucessfully deleted
homeDirSSH = os.path.expanduser("~/.ssh")
os.system("sudo rm -rf /usr/local/bin/connect")
os.system("rm "+homeDirSSH+"/connections.txt")
if(not (os.path.isfile("/usr/local/bin/connect") and os.path.isfile(homeDirSSH+"/connections.txt"))):
    print("Server Connect uninstalled sucessfully")
else:
    print("An error occured")
