#!/usr/bin/python3
#######################################################################
#                                                                     #
# This is an the uninstall script to remove Server Connect to         #
# eliminate having to do it manually.                                 #
#                                                                     #
#######################################################################

import os
homeDirSSH = os.path.expanduser("~/.ssh")

serverConnectFiles = ["/usr/local/bin/connect", "/usr/local/bin/connect.py"]
connectionsFiles = [homeDirSSH+'/connections.txt', 
    homeDirSSH+'/connections.dat',
    homeDirSSH+'/connections.txt.bak']
successfullyRemoved = []

# Deletes connect from /usr/local/bin and connections.txt/.dat/txt.bak
# from the ~/.ssh folder and verifies they both have been
# sucessfully deleted
for f in serverConnectFiles:
    if(os.path.isfile(f)):
        os.system("rm -rf "+f)
        successfullyRemoved.append(not os.path.isfile(f))

for f in connectionsFiles:
    if(os.path.isfile(f)):
        os.system("rm -rf "+f)
        successfullyRemoved.append(not os.path.isfile(f))

if(all(successfullyRemoved)):
    print("Server Connect uninstalled sucessfully")
else:
    for x in successfullyRemoved:
        print(x)
    print("An error occured")
