#!/usr/bin/python3
#######################################################################
#                                                                     #
# This is an the uninstall script to remove Server Connect to         #
# eliminate having to do it manually.                                 #
#                                                                     #
#######################################################################

import os
homeDirSSH = os.path.expanduser("~/.ssh")

connectionsFiles = [homeDirSSH+'/connections.txt', homeDirSSH+'/connections.dat', homeDirSSH+'/connections.txt.bak']
successfullyRemoved = []

# Deletes connect from /usr/local/bin and connections.txt/.dat/txt.bak
# from the ~/.ssh folder and verifies they both have been
# sucessfully deleted
os.system("sudo rm -rf /usr/local/bin/connect")
for f in connectionsFiles:
    os.system("rm -rf "+f)
    successfullyRemoved.append(os.path.isfile(f))

if(not (os.path.isfile("/usr/local/bin/connect") and all(successfullyRemoved))):
    print("Server Connect uninstalled sucessfully")
else:
    print("An error occured")
